name: Show Hello File

on:
  push:
    branches:
      - main

jobs:
  display-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display hello.txt content
        run: cat hello.txt
